### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [kevinkace/posthtml-pseudo#28]
@kevinkace Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by kevinkace** [comment]
I'd be happy to have it listed with other plugins at https://github.com/posthtml/posthtml#plugins

As for transferring to the org, that's something I'd have to think about, and ATM I'm not ready to make that move.

Let me know if there's anything required to get it listed with the other plugins.

**Comment by Scrum** [comment]
> Let me know if there's anything required to get it listed with the other plugins.

it is enough to make the PR in posthtml with the addition of your package. Regarding the second method, you can see the [documentation](https://github.com/posthtml/posthtml-plugins/#how-to-add-a-plugin) how to add to another list

> As for transferring to the org, that's something I'd have to think about, and ATM I'm not ready to make that move.

Yes it is reasonable, in any case let me know if you decide something

**Comment by kevinkace** [comment]
Thanks for the tips. I've submitted a PR :)

**Comment by Scrum** [comment]
you're welcome
